
CREATE TABLE slot
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time              VARCHAR(100),
    vaccine_center_id INTEGER,
    enable            BOOLEAN,
    CONSTRAINT pk_slot PRIMARY KEY (id)
);

CREATE TABLE appointment
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vaccine_center_id INTEGER,
    patient_id        INTEGER,
    vaccine_id        INTEGER,
    time              VARCHAR(255),
    CONSTRAINT pk_appointment PRIMARY KEY (id)
);

